module.exports = {
  AuthService: require('./auth.service'),
  BookBankBranchService: require('./book-bank-branch.service'),
  BookBankService: require('./book-bank.service'),
  BranchService: require('./branch.service'),
  CompanyService: require('./company.service'),
  InvoiceSupplierService: require('./invoice-supplier.service'),
  LicenseService: require('./license.service'),
  NotifyService: require('./notify.service'),
  PaymentService: require('./payment.service'),
  PaymentLogService: require('./payment-log.service'),
  ProductService: require('./product.service'),
  ReportInvoiceService: require('./report-invoice.service'),
  ReportPaymentService: require('./report-payment.service'),
  ReportProductService: require('./report-product.service'),
  SupplierService: require('./supplier.service'),
  SyncDataLogService: require('./sync-data-log.service'),
  SyncDataService: require('./sync-data.service'),
  UserBranchService: require('./user-branch.service'),
  UserService: require('./user.service'),
}