module.exports = {
  BankModel: require('./bank.model'),
  BookBankBranchModel: require('./book-bank-branch.model'),
  BookBankModel: require('./book-bank.model'),
  BranchModel: require('./branch.model'),
  CompanyModel: require('./company.model'),
  InvoiceSupplierListModel: require('./invoice-supplier-list.model'),
  InvoiceSupplierModel: require('./invoice-supplier.model'),
  LicenseNotifyModel: require('./license-notify.model'),
  LicenseModel: require('./license.model'),
  MenuModel: require('./menu.model'),
  NotifyEventModel: require('./notify-event.model'),
  NotifyRecipientModel: require('./notify-recipient.model'),
  NotifyModel: require('./notify.model'),
  OnesignalPlayerModel: require('./onesignal-player.model'),
  PaymentModel: require('./payment.model'),
  PaymentLogModel: require('./payment-log.model'),
  PermissionModel: require('./permission.model'),
  ProductModel: require('./product.model'),
  ProductCategoryModel: require('./product-category.model'),
  ProductTypeModel: require('./product-type.model'),
  SupplierModel: require('./supplier.model'),
  SyncDataLogModel: require('./sync-data-log.model'),
  SyncDataModel: require('./sync-data.model'),
  UserBranchModel: require('./user-branch.model'),
  UserModel: require('./user.model'),
}